apiVersion: v1
kind: Pod
metadata:
  name: pod-vault
spec:
  initContainers:
    - name: hashivault
      image: pavanidevops78/kubernetes:1.1
      env:
        - name: VAULT_ADDR
          value: https://54.167.202.14:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/vault
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  containers:
    - name: backend
      image: pavanidevops78/kubernetes:1.0
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  volumes:
    - name: vault-secret
      emptyDir: {}


