apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    appName: backend
    projectName: expense
spec:
  initContainers:
    - name: get-secrets
      image:  public.ecr.aws/u4j6q5s8/kubernetes-vault-init-container:1.2
      env:
        - name: VAULT_ADDR
          value: https://vault-internal.pdevops72.online:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/vault
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - name: vault-secret
          mountPath: /data
    - name: schema
      image: public.ecr.aws/u4j6q5s8/backend-schema:1.4

      volumeMounts:
        - name: vault-secret
          mountPath: /data


  containers:
    - name: backend
      image: public.ecr.aws/u4j6q5s8/expense-backend:1.0
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  volumes:
    - name: vault-secret
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    appName: backend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP