apiVersion: v1
kind: Pod
metadata:
  name: backend

spec:
  initContainers:
    - name: get-secrets
      image: docker.io/pavanidevops78/kubernetes:1.6
      env:
        - name: VAULT_ADDR
          value: https://34.207.214.80:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/vault
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - name: vault-secret
          mountPath: /data
    - name: backend-schema
      image: pavanidevops78/kubernetes:1.8
      volumeMounts:
        - name: vault-secret
          mountPath: /data


  containers:
    - name: backend
      image:  pavanidevops78/kubernetes:1.7
      volumeMounts:
        - name: vault-secret
          mountPath: /data
  volumes:
    - name: vault-secret
      emptyDir: {}


