apiVersion: v1
kind: Pod
metadata:
  name: ephemeral
spec:
  containers:
    - name: sidecar
      image: gcr.io/distroless/nodejs-debian11
      command:
        - /nodejs/bin/node
        - -e
        - 'setTimeout(() => console.log("done"), 999999)'



