apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: frontend
    projectName: expense
spec:
  containers:
    - name: frontend
      image: pavanidevops78/kubernetes:2.3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    appName: frontend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
