apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    appName: frontend
    projectName: expense
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/u4j6q5s8/expense-frontend:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: frontend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
