---
apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: service-01
spec:
  selector:
    appName: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod-01
#  labels:
#    appName: nginx
#spec:
#  containers:
#    - name: nginx
#      image:

# curl nginx

