apiVersion: v1
kind: Pod
metadata:
  name: sharedata
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
    - name: nginx-content
      image: pavanidevops78/kubernetes:v1
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html

  volumes:
    - name: nginx-path
      emptyDir: {}
