apiVersion: v1
kind: Pod
metadata:
  name: volume_mounts
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-path
      emptyDir: {}